- name: check local config
  delegate_to: localhost
  stat:
    path: files/{{ inventory_hostname }}/iptables.conf
  register: iptables_config

- name: install
  include_tasks: install.yml
  when: iptables_config.stat.exists

- name: config
  include_tasks: config.yml
  when: iptables_config.stat.exists
